# Generated by Django 5.1.1 on 2024-11-06 19:41

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
        migrations.AddField(
            model_name='department',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
    ]
